
// This file has been generated by the GUI designer. Do not modify.
namespace ScreenLapse
{
	public partial class ScrotViewer
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView dayAvailTreeView;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button playPauseButton;

		private global::Gtk.HScale timeSlider;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ScreenLapse.ScrotViewer
			this.Name = "ScreenLapse.ScrotViewer";
			this.Title = global::Mono.Unix.Catalog.GetString ("ScrotViewer");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ScreenLapse.ScrotViewer.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.WidthRequest = 161;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.dayAvailTreeView = new global::Gtk.TreeView ();
			this.dayAvailTreeView.CanFocus = true;
			this.dayAvailTreeView.Name = "dayAvailTreeView";
			this.GtkScrolledWindow.Add (this.dayAvailTreeView);
			this.hbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w3.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.playPauseButton = new global::Gtk.Button ();
			this.playPauseButton.CanFocus = true;
			this.playPauseButton.Name = "playPauseButton";
			this.playPauseButton.UseUnderline = true;
			this.playPauseButton.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox2.Add (this.playPauseButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.playPauseButton]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.timeSlider = new global::Gtk.HScale (null);
			this.timeSlider.CanFocus = true;
			this.timeSlider.Name = "timeSlider";
			this.timeSlider.Adjustment.Upper = 100;
			this.timeSlider.Adjustment.PageIncrement = 10;
			this.timeSlider.Adjustment.StepIncrement = 1;
			this.timeSlider.Adjustment.Value = 100;
			this.timeSlider.DrawValue = true;
			this.timeSlider.Digits = 0;
			this.timeSlider.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox2.Add (this.timeSlider);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.timeSlider]));
			w5.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w7.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w8.Position = 0;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 785;
			this.DefaultHeight = 582;
			this.Show ();
		}
	}
}
