// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ScreenLapse {
    
    
    public partial class ScrotViewer {
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView dayAvailTreeView;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Image scrotDisplayArea;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Button playPauseButton;
        
        private Gtk.HScale timeSlider;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ScreenLapse.ScrotViewer
            this.Name = "ScreenLapse.ScrotViewer";
            this.Title = Mono.Unix.Catalog.GetString("ScrotViewer");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child ScreenLapse.ScrotViewer.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.WidthRequest = 161;
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.dayAvailTreeView = new Gtk.TreeView();
            this.dayAvailTreeView.CanFocus = true;
            this.dayAvailTreeView.Name = "dayAvailTreeView";
            this.GtkScrolledWindow.Add(this.dayAvailTreeView);
            this.hbox1.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.scrotDisplayArea = new Gtk.Image();
            this.scrotDisplayArea.WidthRequest = 603;
            this.scrotDisplayArea.HeightRequest = 451;
            this.scrotDisplayArea.Name = "scrotDisplayArea";
            this.vbox3.Add(this.scrotDisplayArea);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.scrotDisplayArea]));
            w3.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.playPauseButton = new Gtk.Button();
            this.playPauseButton.CanFocus = true;
            this.playPauseButton.Name = "playPauseButton";
            this.playPauseButton.UseUnderline = true;
            this.playPauseButton.Label = Mono.Unix.Catalog.GetString("GtkButton");
            this.hbox2.Add(this.playPauseButton);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.playPauseButton]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.timeSlider = new Gtk.HScale(null);
            this.timeSlider.CanFocus = true;
            this.timeSlider.Name = "timeSlider";
            this.timeSlider.Adjustment.Upper = 100;
            this.timeSlider.Adjustment.PageIncrement = 10;
            this.timeSlider.Adjustment.StepIncrement = 1;
            this.timeSlider.DrawValue = true;
            this.timeSlider.Digits = 0;
            this.timeSlider.ValuePos = ((Gtk.PositionType)(2));
            this.hbox2.Add(this.timeSlider);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.timeSlider]));
            w5.Position = 1;
            this.vbox3.Add(this.hbox2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            this.hbox1.Add(this.vbox3);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 776;
            this.DefaultHeight = 589;
            this.Show();
        }
    }
}
