
// This file has been generated by the GUI designer. Do not modify.
namespace ScreenLapse
{
	public partial class ScrotViewer
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView dayAvailTreeView;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button button5;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button playPauseButton;

		private global::Gtk.HScale timeSlider;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ScreenLapse.ScrotViewer
			this.Name = "ScreenLapse.ScrotViewer";
			this.Title = global::Mono.Unix.Catalog.GetString ("ScrotViewer");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ScreenLapse.ScrotViewer.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.WidthRequest = 161;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.dayAvailTreeView = new global::Gtk.TreeView ();
			this.dayAvailTreeView.CanFocus = true;
			this.dayAvailTreeView.Name = "dayAvailTreeView";
			this.GtkScrolledWindow.Add (this.dayAvailTreeView);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			// Container child button5.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Delete Day");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.button5.Add (w3);
			this.hbox4.Add (this.button5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button5]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w14.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.playPauseButton = new global::Gtk.Button ();
			this.playPauseButton.CanFocus = true;
			this.playPauseButton.Name = "playPauseButton";
			this.playPauseButton.UseUnderline = true;
			this.playPauseButton.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox2.Add (this.playPauseButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.playPauseButton]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.timeSlider = new global::Gtk.HScale (null);
			this.timeSlider.CanFocus = true;
			this.timeSlider.Name = "timeSlider";
			this.timeSlider.Adjustment.Upper = 100;
			this.timeSlider.Adjustment.PageIncrement = 10;
			this.timeSlider.Adjustment.StepIncrement = 1;
			this.timeSlider.Adjustment.Value = 100;
			this.timeSlider.DrawValue = true;
			this.timeSlider.Digits = 0;
			this.timeSlider.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox2.Add (this.timeSlider);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.timeSlider]));
			w16.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w18.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w19.Position = 0;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 785;
			this.DefaultHeight = 582;
			this.Show ();
			this.button5.Clicked += new global::System.EventHandler (this.DeleteDayClicked);
		}
	}
}
